"""Typed request and response schemas for the agent layer.

All agent I/O is validated through these Pydantic models so that callers
can rely on the shape of every response and detect failures without
inspecting free-form text.

Design notes
------------
* ``AgentRequest`` / ``AgentResponse`` mirror the ``MCPRequest`` /
  ``MCPResponse`` base classes to keep the tracing story (``request_id``,
  ``timestamp``) consistent across layers.
* ``summary`` is a deterministic, human-readable string produced by the
  agent service.  It is never generated by an LLM in the current
  implementation.
* Error responses set ``success=False`` and populate ``error_message``;
  all numeric / datetime fields fall back to their ``default`` values so
  that schema validation still passes on the error path.
"""

from __future__ import annotations

from datetime import UTC, datetime

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Request schemas
# ---------------------------------------------------------------------------


class AgentRequest(BaseModel):
    """Base class for all agent requests."""

    request_id: str = Field(..., description="Unique request identifier for tracing")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Request creation timestamp",
    )


class SignalReviewRequest(AgentRequest):
    """Request a deterministic review of one or more signals.

    The agent resolves each signal ID against the registry, runs the signal
    engine against the current macro snapshot, and returns a schema-validated
    summary.
    """

    signal_ids: list[str] = Field(
        ...,
        min_length=1,
        description="Signal definition IDs to review (must be non-empty)",
    )
    country: str = Field(default="US", description="Country code (ISO 3166-1 alpha-2)")


class MacroSnapshotSummaryRequest(AgentRequest):
    """Request a deterministic summary of the current macro snapshot.

    The agent fetches the latest macro snapshot for the given country and
    formats the result into a schema-validated summary.
    """

    country: str = Field(default="US", description="Country code (ISO 3166-1 alpha-2)")


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class AgentResponse(BaseModel, extra="forbid"):
    """Base class for all agent responses."""

    request_id: str = Field(..., description="Echo of the request ID that triggered this response")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Response creation timestamp",
    )
    success: bool = Field(default=True, description="Whether the agent operation succeeded")
    error_message: str | None = Field(
        default=None,
        description="Error message if success is False",
    )
    summary: str = Field(
        default="",
        description="Deterministic human-readable summary of the agent output",
    )


class SignalReviewResponse(AgentResponse):
    """Schema-validated result of a signal review.

    Carries the engine metadata forwarded from the MCP layer alongside the
    agent-generated ``summary``.
    """

    engine_run_id: str = Field(
        default="",
        description="Unique ID of the signal engine run (empty on error)",
    )
    signals_generated: int = Field(default=0, description="Total number of signals produced")
    buy_signals: int = Field(default=0, description="Count of BUY signals")
    sell_signals: int = Field(default=0, description="Count of SELL signals")
    hold_signals: int = Field(default=0, description="Count of HOLD signals")
    execution_time_ms: float = Field(
        default=0.0,
        description="Signal engine wall-clock time in milliseconds",
    )


class MacroSnapshotSummaryResponse(AgentResponse):
    """Schema-validated result of a macro snapshot summary.

    Carries snapshot metadata forwarded from the MCP layer alongside the
    agent-generated ``summary``.
    """

    country: str = Field(default="", description="Country code for which the snapshot was fetched")
    snapshot_timestamp: datetime | None = Field(
        default=None,
        description="Reference time of the macro snapshot; None on error",
    )
    features_count: int = Field(
        default=0,
        description="Number of macro features present in the snapshot",
    )
